insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@garyachew', 205, 'Wine - Rubyport', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@ponomareva_sasha', 851, 'Chicken - Whole Roasting', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@hellrs', 600, 'Liqueur Banana, Ramazzotti', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@hellrs', 659, 'Wine - Tribal Sauvignon', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@hellrs', 460, 'Carbonated Water - Strawberry', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@Zviiiry', 589, 'Chickhen - Chicken Phyllo', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@garyachew', 307, 'Oregano - Fresh', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@nikolskayaos', 260, 'Cheese - Brick With Onion', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@ponomareva_sasha', 608, 'Kahlua', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@hellrs', 132, 'Tart - Raisin And Pecan', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@garyachew', 383, 'Wanton Wrap', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@ponomareva_sasha', 393, 'Muffin - Mix - Creme Brule 15l', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@hellrs', 281, 'Bowl 12 Oz - Showcase 92012', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@garyachew', 772, 'Nacho Chips', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@ponomareva_sasha', 254, 'Paper - Brown Paper Mini Cups', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@hellrs', 987, 'Pasta - Cappellini, Dry', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@nikolskayaos', 822, 'Beer - Original Organic Lager', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@hellrs', 582, 'Longos - Lasagna Beef', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@garyachew', 763, 'Ice Cream - Fudge Bars', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@nikolskayaos', 685, 'Tomatoes - Orange', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@Zviiiry', 394, 'Wine - Red, Mouton Cadet', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@hellrs', 484, 'Sauce - Demi Glace', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@garyachew', 110, 'Energy Drink', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@nikolskayaos', 604, 'Pork - Back, Long Cut, Boneless', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@ponomareva_sasha', 810, 'Wine - Hardys Bankside Shiraz', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@ponomareva_sasha', 346, 'Table Cloth - 53x69 Colour', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@hellrs', 679, 'Beef - Flank Steak', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@garyachew', 248, 'Energy Drink Bawls', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@garyachew', 308, 'Soup - Campbells', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@Zviiiry', 827, 'Tahini Paste', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@ponomareva_sasha', 250, 'Fish - Scallops, Cold Smoked', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@ponomareva_sasha', 667, 'Flavouring - Rum', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@hellrs', 408, 'Lettuce - Romaine, Heart', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@hellrs', 286, 'Yoplait - Strawbrasp Peac', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@hellrs', 786, 'The Pop Shoppe Pinapple', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@Zviiiry', 640, 'Mushroom - Enoki, Fresh', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@ponomareva_sasha', 609, 'Pastry - Cheese Baked Scones', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@garyachew', 362, 'Green Tea Refresher', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@Zviiiry', 854, 'Shiratamako - Rice Flour', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@ponomareva_sasha', 597, 'Soap - Pine Sol Floor Cleaner', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@hellrs', 598, 'Flour - Bran, Red', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@ponomareva_sasha', 941, 'Lady Fingers', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@garyachew', 781, 'Cheese - La Sauvagine', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@ponomareva_sasha', 159, 'Sobe - Liz Blizz', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@hellrs', 967, 'Wine - White, Mosel Gold', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@hellrs', 497, 'Pepper - Cayenne', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@Zviiiry', 333, 'Lobak', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@ponomareva_sasha', 446, 'Cheese - Grana Padano', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@ponomareva_sasha', 649, 'Lamb Shoulder Boneless Nz', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@Zviiiry', 980, 'Beef - Texas Style Burger', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@garyachew', 648, 'Coffee - Flavoured', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@nikolskayaos', 234, 'Chicken - White Meat, No Tender', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@garyachew', 951, 'Bagel - Sesame Seed Presliced', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@nikolskayaos', 649, '7up Diet, 355 Ml', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@ponomareva_sasha', 339, 'Roe - Flying Fish', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@garyachew', 328, 'Blueberries', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@Zviiiry', 801, 'V8 Splash Strawberry Kiwi', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@Zviiiry', 863, 'Cherries - Frozen', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@nikolskayaos', 520, 'Soup - Campbells, Minestrone', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@hellrs', 593, 'Cabbage Roll', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@garyachew', 848, 'Table Cloth 81x81 Colour', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@nikolskayaos', 747, 'Oil - Shortening,liqud, Fry', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@nikolskayaos', 746, 'Kahlua', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@garyachew', 102, 'Mix - Cocktail Ice Cream', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@nikolskayaos', 213, 'Cheese - La Sauvagine', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@hellrs', 596, 'Potatoes - Peeled', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@ponomareva_sasha', 380, 'Pepsi - Diet, 355 Ml', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@nikolskayaos', 917, 'Fondant - Icing', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@hellrs', 255, 'Corn Syrup', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@ponomareva_sasha', 920, 'Cheese - Stilton', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@ponomareva_sasha', 116, 'Carbonated Water - Raspberry', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@nikolskayaos', 612, 'Beer - Steamwhistle', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@Zviiiry', 272, 'Beef - Top Butt Aaa', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@nikolskayaos', 958, 'Pork - Caul Fat', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@hellrs', 167, 'Island Oasis - Peach Daiquiri', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@garyachew', 406, 'Calypso - Black Cherry Lemonade', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@garyachew', 388, 'Wine - Red, Cabernet Merlot', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@garyachew', 123, 'Lentils - Red, Dry', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@ponomareva_sasha', 833, 'Pasta - Cannelloni, Sheets, Fresh', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@nikolskayaos', 423, 'Urban Zen Drinks', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@garyachew', 654, 'Sauce - White, Mix', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@nikolskayaos', 137, 'Pastry - Cherry Danish - Mini', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@hellrs', 253, 'Grouper - Fresh', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@ponomareva_sasha', 661, 'Soup - French Onion', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@garyachew', '@hellrs', 282, 'Alize Sunset', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@ponomareva_sasha', 973, 'Cheese - St. Andre', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@ponomareva_sasha', 982, 'Beef - Ground Lean Fresh', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@hellrs', 260, 'Creme De Menthe Green', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@nikolskayaos', 108, 'Hot Choc Vending', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@nikolskayaos', 691, 'Puff Pastry - Sheets', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@Zviiiry', 211, 'Cheese - Havarti, Roasted Garlic', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@garyachew', 854, 'Doilies - 8, Paper', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@nikolskayaos', '@nikolskayaos', 891, 'Ecolab Digiclean Mild Fm', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@ponomareva_sasha', 611, 'Lid Tray - 12in Dome', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@ponomareva_sasha', '@hellrs', 580, 'Pork Loin Bine - In Frenched', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@nikolskayaos', 362, 'Ecolab - Mikroklene 4/4 L', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@ponomareva_sasha', 374, 'Scrubbie - Scotchbrite Hand Pad', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@ponomareva_sasha', 834, 'Miso - Soy Bean Paste', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@Zviiiry', '@garyachew', 325, 'Coffee Cup 12oz 5342cd', 4);
insert into debt (user_debtor, user_creditor, amount, description, payment_id) values ('@hellrs', '@nikolskayaos', 391, 'Chips Potato Swt Chilli Sour', 4);
